In [ ]:
from dotenv import load_dotenv
load_dotenv()

import os
import requests
import pandas as pd

pd.set_option('display.max_colwidth', None)

pd.set_option('display.max_columns', None)

gameName = ''
tagLine = ''
api_key = os.environ.get('riot_api_key')

def get_puuid(gameName=None, tagLine=None, api_key=None):
    link = f'https://americas.api.riotgames.com/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}?api_key={api_key}'

    response = requests.get(link)
    return response.json()['puuid']

def get_name_tag(puuid=None, api_key=None):
    link = f'https://americas.api.riotgames.com/riot/account/v1/accounts/by-puuid/{puuid}?api_key={api_key}'

    response = requests.get(link)
    GameName = response.json()['gameName']
    TagLine = response.json()['tagLine']

    return f'{GameName}#{TagLine}'

def get_ladder(top=None):
    root = 'https://na1.api.riotgames.com/'
    chall = 'lol/league/v4/challengerleagues/by-queue/RANKED_SOLO_5x5'
    gm = 'lol/league/v4/grandmasterleagues/by-queue/RANKED_SOLO_5x5'
    master = 'lol/league/v4/masterleagues/by-queue/RANKED_SOLO_5x5'

    chall_response = requests.get(root + chall + '?api_key=' + api_key)
    gm_response = requests.get(root + gm + '?api_key=' + api_key)
    master_response = requests.get(root + master + '?api_key=' + api_key)

    chall_df = pd.DataFrame(chall_response.json()['entries']).sort_values('leaguePoints', ascending=False).reset_index(drop=True)
    gm_df = pd.DataFrame(gm_response.json()['entries']).sort_values('leaguePoints', ascending=False).reset_index(drop=True)
    master_df = pd.DataFrame(master_response.json()['entries']).sort_values('leaguePoints', ascending=False).reset_index(drop=True)

    ladder = pd.concat([chall_df, gm_df, master_df])[:top].reset_index(drop=True)
    ladder = ladder.drop(columns = 'rank').reset_index(drop=False).rename(columns={'index': 'rank'})
    ladder['rank'] = ladder['rank'] + 1

    return ladder

def get_match_history(region=None, puuid=None, start=0, count=20):
    root_url = f'https://{region}.api.riotgames.com/'
    endpoint = f'lol/match/v5/matches/by-puuid/{puuid}/ids'
    query_params = f'?start={start}&count={count}'

    response = requests.get(root_url + endpoint + query_params + '&api_key=' + api_key)
    
    return response.json()

def get_match_data_from_id(region=None, match_id=None):
    root_url = f'https://{region}.api.riotgames.com/'
    endpoint = f'lol/match/v5/matches/{match_id}'

    response = requests.get(root_url + endpoint + '?api_key=' + api_key)
    
    return response.json()

In [4]:
get_ladder(top=3000)

,rank,puuid,leaguePoints,wins,losses,veteran,inactive,freshBlood,hotStreak
0,1,TAKCv8Bg43_R7se1806uFc5MW_ZH9tcjAbxkx9HCrjwfD4zX9QBM_zv6oQ9gcJEENl1rr-v4e84Bkg,855,104,24,False,False,True,False
1,2,Fr13MrbTXNdr55Zy96MCHRvqPUvWVUV0w4DSvE__A2lZNXl1UYL_jECYNP9KD_IzuFh0q79hJbVwfQ,824,148,65,False,False,True,True
2,3,kqpJK0Zp7-t1NUrp-CNwkdzAC_Plk1qq-Uc8UtRCZcSllb3GBrsFAP9D0bSj0eFhRouoTB_kcD2SzQ,810,402,311,False,False,True,False
3,4,YLgM0EbM3emykEeKKQrhcne3DcNjhPmulIJBNE5cyJ989VzwtpAqgTf3EkqgpuYjki4jMQwg_LxWgw,546,216,165,True,False,False,False
4,5,BuQerXTF5J8PfS6QbPWKbpct97VT6Z_69_a0qCJD5vwucEBrMbgb7IttuZxcmGrnyCucMk9_E9diNw,480,184,140,False,False,False,True
...,...,...,...,...,...,...,...,...,...
2995,2996,yTHQd0Mr3j-6AIu49NovRSauC1CMReh4RnGIAvO2-4P3kX8xZBs4IlUFI0T1_d2H7Dkv1ISiNOAwXg,60,310,290,True,False,False,False
2996,2997,MSN_TrJ4moQD2haTLQdUW3UXoRbPcslOSMjTgQ9Qlm--l6DYgzD0Sn3UNV5V0GxxK4ZWP4ugZFt9HA,60,308,307,True,False,False,False
2997,2998,S56vMNVKhw97lno4b_B2lESeC2FeiuI7WDflwO2UtD268kfqdFbfMMm7lHHKEObfpSx6g5jqhzrCdQ,60,306,283,False,False,False,False
2998,2999,_sSrXk8uo7pMbyDpfrPMMzWtMbwDe3fayzyNnvXdkSwMCe6G-2MaPfC3T1sq31Y4OX7E_18yqRE9Rw,60,304,287,False,False,True,False
2999,3000,-eHs9cXqZL_IskcvDSoPLLqLRcl691wiCvrVTdMJDdRqNhkypQjd4KSEwc1mCDp8xjof3VkrdpcYZg,60,296,283,False,False,True,False

In [5]:
def process_match_json(match_json, puuid):
    metadata = match_json['metadata']
    info = match_json['info']
    players = info['participants']

    match_id = metadata['matchId']
    participants = metadata['participants']
    teams = info['teams']


    player = players[participants.index(puuid)]


    # -------------------------
    # Match information
    # -------------------------

    game_creation = info['gameCreation']
    game_duration = info['gameDuration']
    game_start_timestamp = info['gameStartTimestamp']
    game_end_timestamp = info['gameEndTimestamp']
    patch = info['gameVersion']


    # -------------------------
    # Player identity
    # -------------------------

    riot_id = player['riotIdGameName']
    riot_tag = player['riotIdTagline']
    summoner_id = player['summonerId']
    summoner_name = player['summonerName']


    # -------------------------
    # Target variable
    # -------------------------

    win = player['win']


    # -------------------------
    # Team identity
    # Riot uses teamId 100 and 200 instead of "team 1" and "team 2".
    # 100 is usually blue side, 200 is usually red side.
    # -------------------------

    team_id = player['teamId']

    if team_id == 100:
        enemy_team_id = 200
        side = 'blue'
    else:
        enemy_team_id = 100
        side = 'red'


    # -------------------------
    # Champion information
    # -------------------------

    champion_id = player['championId']
    champion_name = player['championName']
    champion_transform = player['championTransform']


    # -------------------------
    # Gold and farming
    # -------------------------

    gold_earned = player['goldEarned']
    neutral_minions_killed = player['neutralMinionsKilled']
    total_minions_killed = player['totalMinionsKilled']
    cs_total = neutral_minions_killed + total_minions_killed
    cs_per_min = cs_total / (game_duration / 60)


    # -------------------------
    # KDA
    # -------------------------

    kills = player['kills']
    deaths = player['deaths']
    assists = player['assists']
    firstblood = player['firstBloodKill']
    kda = (kills + assists) / max(1, deaths)


    # -------------------------
    # Damage
    # -------------------------

    total_damage_dealt = player['totalDamageDealt']
    total_damage_dealt_to_champions = player['totalDamageDealtToChampions']
    total_damage_shielded = player['totalDamageShieldedOnTeammates']
    total_damage_taken = player['totalDamageTaken']
    total_heal = player['totalHeal']
    total_time_cc_dealt = player['totalTimeCCDealt']


    # -------------------------
    # Surrender
    # -------------------------

    early_surrender = player['gameEndedInEarlySurrender']
    surrender = player['gameEndedInSurrender']


    # -------------------------
    # Items
    # -------------------------

    item0 = player['item0']
    item1 = player['item1']
    item2 = player['item2']
    item3 = player['item3']
    item4 = player['item4']
    item5 = player['item5']
    item6 = player['item6']


    # -------------------------
    # Objectives stolen
    # -------------------------

    objectives_stolen = player['objectivesStolen']
    objectives_stolen_assists = player['objectivesStolenAssists']


    # -------------------------
    # Summoner spells
    # -------------------------

    summoner1_id = player['summoner1Id']
    summoner2_id = player['summoner2Id']


    # -------------------------
    # Vision
    # -------------------------

    wards_placed = player['wardsPlaced']
    wards_killed = player['wardsKilled']
    vision_score = player['visionScore']
    detector_wards_placed = player['detectorWardsPlaced']


    # -------------------------
    # Role / position
    # -------------------------

    role = player['role']
    lane = player['lane']
    team_position = player['teamPosition']



    # -------------------------
    # Team-level first blood
    # If any player on your team has firstBloodKill == True,
    # then your team got first blood.
    # -------------------------

    team_first_blood = False
    enemy_first_blood = False
    first_blood_team_id = None
    first_blood_champion = None

    for p in players:
        if p['firstBloodKill'] == True:
            first_blood_team_id = p['teamId']
            first_blood_champion = p['championName']

            if p['teamId'] == team_id:
                team_first_blood = True
            else:
                enemy_first_blood = True


    # -------------------------
    # Team totals
    # These compare your player's team against the enemy team.
    # Useful for simple win/loss modeling.
    # -------------------------

    team_kills = 0
    team_deaths = 0
    team_assists = 0
    team_gold = 0
    team_damage_to_champions = 0
    team_vision_score = 0

    enemy_kills = 0
    enemy_deaths = 0
    enemy_assists = 0
    enemy_gold = 0
    enemy_damage_to_champions = 0
    enemy_vision_score = 0

    for p in players:
        if p['teamId'] == team_id:
            team_kills = team_kills + p['kills']
            team_deaths = team_deaths + p['deaths']
            team_assists = team_assists + p['assists']
            team_gold = team_gold + p['goldEarned']
            team_damage_to_champions = team_damage_to_champions + p['totalDamageDealtToChampions']
            team_vision_score = team_vision_score + p['visionScore']
        else:
            enemy_kills = enemy_kills + p['kills']
            enemy_deaths = enemy_deaths + p['deaths']
            enemy_assists = enemy_assists + p['assists']
            enemy_gold = enemy_gold + p['goldEarned']
            enemy_damage_to_champions = enemy_damage_to_champions + p['totalDamageDealtToChampions']
            enemy_vision_score = enemy_vision_score + p['visionScore']


    kill_difference = team_kills - enemy_kills
    gold_difference = team_gold - enemy_gold
    damage_difference = team_damage_to_champions - enemy_damage_to_champions
    vision_difference = team_vision_score - enemy_vision_score



    # -------------------------
    # Team objectives
    # -------------------------

    for team in teams:

        if team['teamId'] == team_id:
            team_objs = team['objectives']
        else:
            enemy_objs = team['objectives']


    barons = team_objs['baron']
    dragons = team_objs['dragon']
    grubs = team_objs.get('horde', {'first': False, 'kills': 0})
    heralds = team_objs['riftHerald']
    inhibitors = team_objs['inhibitor']
    towers = team_objs['tower']

    enemy_barons = enemy_objs['baron']
    enemy_dragons = enemy_objs['dragon']
    enemy_grubs = enemy_objs.get('horde', {'first': False, 'kills': 0})
    enemy_heralds = enemy_objs['riftHerald']
    enemy_inhibitors = enemy_objs['inhibitor']
    enemy_towers = enemy_objs['tower']


    baron_first = barons['first']
    baron_kills = barons['kills']

    dragon_first = dragons['first']
    dragon_kills = dragons['kills']

    grub_first = grubs['first']
    grub_kills = grubs['kills']

    herald_first = heralds['first']
    herald_kills = heralds['kills']

    inhibitor_first = inhibitors['first']
    inhibitor_kills = inhibitors['kills']

    tower_first = towers['first']
    tower_kills = towers['kills']


    enemy_baron_first = enemy_barons['first']
    enemy_baron_kills = enemy_barons['kills']

    enemy_dragon_first = enemy_dragons['first']
    enemy_dragon_kills = enemy_dragons['kills']

    enemy_grub_first = enemy_grubs['first']
    enemy_grub_kills = enemy_grubs['kills']

    enemy_herald_first = enemy_heralds['first']
    enemy_herald_kills = enemy_heralds['kills']

    enemy_inhibitor_first = enemy_inhibitors['first']
    enemy_inhibitor_kills = enemy_inhibitors['kills']

    enemy_tower_first = enemy_towers['first']
    enemy_tower_kills = enemy_towers['kills']


    dragon_difference = dragon_kills - enemy_dragon_kills
    baron_difference = baron_kills - enemy_baron_kills
    grub_difference = grub_kills - enemy_grub_kills
    herald_difference = herald_kills - enemy_herald_kills
    inhibitor_difference = inhibitor_kills - enemy_inhibitor_kills
    tower_difference = tower_kills - enemy_tower_kills



    # -------------------------
    # Put everything into one row
    # -------------------------

    row = {
        'match_id': match_id,
        'game_creation': game_creation,
        'game_duration': game_duration,
        'game_start_timestamp': game_start_timestamp,
        'game_end_timestamp': game_end_timestamp,
        'patch': patch,

        'puuid': puuid,
        'riot_id': riot_id,
        'riot_tag': riot_tag,
        'summoner_id': summoner_id,
        'summoner_name': summoner_name,

        'win': win,

        'team_id': team_id,
        'enemy_team_id': enemy_team_id,
        'side': side,

        'champion_id': champion_id,
        'champion_name': champion_name,
        'champion_transform': champion_transform,

        'gold_earned': gold_earned,
        'neutral_minions_killed': neutral_minions_killed,
        'total_minions_killed': total_minions_killed,
        'cs_total': cs_total,
        'cs_per_min': cs_per_min,

        'kills': kills,
        'deaths': deaths,
        'assists': assists,
        'firstblood': firstblood,
        'kda': kda,

        'total_damage_dealt': total_damage_dealt,
        'total_damage_dealt_to_champions': total_damage_dealt_to_champions,
        'total_damage_shielded': total_damage_shielded,
        'total_damage_taken': total_damage_taken,
        'total_heal': total_heal,
        'total_time_cc_dealt': total_time_cc_dealt,

        'early_surrender': early_surrender,
        'surrender': surrender,

        'item0': item0,
        'item1': item1,
        'item2': item2,
        'item3': item3,
        'item4': item4,
        'item5': item5,
        'item6': item6,

        'objectives_stolen': objectives_stolen,
        'objectives_stolen_assists': objectives_stolen_assists,

        'summoner1_id': summoner1_id,
        'summoner2_id': summoner2_id,

        'wards_placed': wards_placed,
        'wards_killed': wards_killed,
        'vision_score': vision_score,
        'detector_wards_placed': detector_wards_placed,

        'role': role,
        'lane': lane,
        'team_position': team_position,


        'team_first_blood': team_first_blood,
        'enemy_first_blood': enemy_first_blood,
        'first_blood_team_id': first_blood_team_id,
        'first_blood_champion': first_blood_champion,

        'team_kills': team_kills,
        'team_deaths': team_deaths,
        'team_assists': team_assists,
        'team_gold': team_gold,
        'team_damage_to_champions': team_damage_to_champions,
        'team_vision_score': team_vision_score,

        'enemy_kills': enemy_kills,
        'enemy_deaths': enemy_deaths,
        'enemy_assists': enemy_assists,
        'enemy_gold': enemy_gold,
        'enemy_damage_to_champions': enemy_damage_to_champions,
        'enemy_vision_score': enemy_vision_score,

        'kill_difference': kill_difference,
        'gold_difference': gold_difference,
        'damage_difference': damage_difference,
        'vision_difference': vision_difference,


        'baron_first': baron_first,
        'baron_kills': baron_kills,

        'dragon_first': dragon_first,
        'dragon_kills': dragon_kills,

        'grub_first': grub_first,
        'grub_kills': grub_kills,

        'herald_first': herald_first,
        'herald_kills': herald_kills,

        'inhibitor_first': inhibitor_first,
        'inhibitor_kills': inhibitor_kills,

        'tower_first': tower_first,
        'tower_kills': tower_kills,


        'enemy_baron_first': enemy_baron_first,
        'enemy_baron_kills': enemy_baron_kills,

        'enemy_dragon_first': enemy_dragon_first,
        'enemy_dragon_kills': enemy_dragon_kills,

        'enemy_grub_first': enemy_grub_first,
        'enemy_grub_kills': enemy_grub_kills,

        'enemy_herald_first': enemy_herald_first,
        'enemy_herald_kills': enemy_herald_kills,

        'enemy_inhibitor_first': enemy_inhibitor_first,
        'enemy_inhibitor_kills': enemy_inhibitor_kills,

        'enemy_tower_first': enemy_tower_first,
        'enemy_tower_kills': enemy_tower_kills,


        'dragon_difference': dragon_difference,
        'baron_difference': baron_difference,
        'grub_difference': grub_difference,
        'herald_difference': herald_difference,
        'inhibitor_difference': inhibitor_difference,
        'tower_difference': tower_difference
    }


    # -------------------------
    # Convert one row into a DataFrame
    # -------------------------

    matchdf = pd.DataFrame([row])
    return matchdf

In [ ]:
puuid = ''

In [868]:
match_ids = get_match_history(region='americas', puuid=puuid, start=0, count=40)

In [869]:
df = pd.DataFrame()

for match_id in match_ids:
    game = get_match_data_from_id(region='americas', match_id=match_id)
    matchDF = process_match_json(game, puuid=puuid)

    df = pd.concat([df, matchDF], ignore_index=True)

In [870]:
df

,match_id,game_creation,game_duration,game_start_timestamp,game_end_timestamp,patch,puuid,riot_id,riot_tag,summoner_id,summoner_name,win,team_id,enemy_team_id,side,champion_id,champion_name,champion_transform,gold_earned,neutral_minions_killed,total_minions_killed,cs_total,cs_per_min,kills,deaths,assists,firstblood,kda,total_damage_dealt,total_damage_dealt_to_champions,total_damage_shielded,total_damage_taken,total_heal,total_time_cc_dealt,early_surrender,surrender,item0,item1,item2,item3,item4,item5,item6,objectives_stolen,objectives_stolen_assists,summoner1_id,summoner2_id,wards_placed,wards_killed,vision_score,detector_wards_placed,role,lane,team_position,team_first_blood,enemy_first_blood,first_blood_team_id,first_blood_champion,team_kills,team_deaths,team_assists,team_gold,team_damage_to_champions,team_vision_score,enemy_kills,enemy_deaths,enemy_assists,enemy_gold,enemy_damage_to_champions,enemy_vision_score,kill_difference,gold_difference,damage_difference,vision_difference,baron_first,baron_kills,dragon_first,dragon_kills,grub_first,grub_kills,herald_first,herald_kills,inhibitor_first,inhibitor_kills,tower_first,tower_kills,enemy_baron_first,enemy_baron_kills,enemy_dragon_first,enemy_dragon_kills,enemy_grub_first,enemy_grub_kills,enemy_herald_first,enemy_herald_kills,enemy_inhibitor_first,enemy_inhibitor_kills,enemy_tower_first,enemy_tower_kills,dragon_difference,baron_difference,grub_difference,herald_difference,inhibitor_difference,tower_difference
0,NA1_5552207012,1777768479842,1397,1777768493326,1777769890811,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,134,Syndra,0,10651,0,189,189,8.117394,4,4,10,False,3.500000,136392,18478,0,16550,2210,490,False,False,2031,2503,1056,3173,4645,0,3363,0,0,12,4,8,0,15,0,SOLO,MIDDLE,MIDDLE,False,True,100,Aatrox,34,23,42,55656,97607,116,23,35,31,45026,79342,91,11,10630,18265,25,True,1,True,3,True,3,False,0,True,2,False,9,False,0,False,0,False,0,True,1,False,0,True,3,3,1,3,-1,2,6
1,NA1_5552174640,1777766039424,1963,1777766061627,1777768024695,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,799,Ambessa,0,14653,201,36,237,7.244014,8,9,4,False,1.333333,323024,22989,0,37025,13622,423,False,False,6698,6610,1036,6694,6333,3047,3364,0,0,11,4,12,4,35,3,NONE,JUNGLE,JUNGLE,True,False,100,Anivia,38,43,34,66321,134586,219,43,38,76,74915,129806,220,-5,-8594,4780,-1,True,1,False,1,True,3,True,1,False,0,True,4,False,0,True,4,False,0,False,0,True,3,False,11,-3,1,3,1,-3,-7
2,NA1_5552145422,1777763384816,2192,1777763402998,1777765594625,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,799,Ambessa,0,15056,210,59,269,7.363139,4,9,7,False,1.222222,348470,24777,0,44525,16441,419,False,False,6698,6610,3156,3111,1036,6333,3364,0,0,11,4,3,3,29,2,NONE,JUNGLE,JUNGLE,False,True,200,Zed,28,43,41,70738,128137,251,43,28,71,79266,184677,217,-15,-8528,-56540,34,False,0,True,1,True,3,False,0,False,0,False,4,True,1,False,4,False,0,True,1,True,1,True,8,-3,-1,3,-1,-1,-4
3,NA1_5552124829,1777761201033,1921,1777761219067,1777763140324,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,876,Lillia,0,18780,224,53,277,8.651744,15,5,16,False,6.200000,392004,44491,0,50301,32221,551,False,False,3157,6653,4633,3041,3047,3089,3364,0,0,11,4,6,1,20,0,NONE,JUNGLE,JUNGLE,False,True,100,Ezreal,40,33,59,76010,139459,191,33,40,32,65996,136116,232,7,10014,3343,-41,False,0,False,2,False,0,False,0,True,3,False,11,True,1,True,2,True,3,False,0,False,0,True,6,0,-1,-3,0,3,5
4,NA1_5551721292,1777699609356,1574,1777699629509,1777701203202,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,799,Ambessa,0,12611,187,19,206,7.852605,10,1,7,False,17.000000,279039,24308,0,23594,14112,360,False,True,6698,6696,6333,3047,3035,1036,3364,0,0,11,4,2,2,18,0,NONE,JUNGLE,JUNGLE,False,True,200,Anivia,32,10,42,58469,92384,132,10,32,16,43314,66793,117,22,15155,25591,15,False,0,False,2,True,3,True,1,True,1,True,8,False,0,True,2,False,0,False,0,False,0,False,1,0,0,3,1,1,7
5,NA1_5551699103,1777697824883,1561,1777697838895,1777699400479,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,91,Talon,0,10949,153,22,175,6.726457,4,8,5,False,1.125000,199725,10950,0,26646,7713,344,False,False,6699,6697,1001,3179,1036,0,3364,0,0,11,4,0,2,10,0,NONE,JUNGLE,JUNGLE,False,True,100,KSante,12,35,21,48329,86190,138,35,12,56,61391,87648,158,-23,-13062,-1458,-20,False,0,True,1,False,0,False,0,False,0,False,3,True,1,False,3,True,3,True,1,True,1,True,9,-2,-1,-3,-1,-1,-6
6,NA1_5551643180,1777694100558,1950,1777694116951,1777696066872,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,61,Orianna,0,18533,0,212,212,6.523077,20,7,12,False,4.571429,227630,58433,3356,28517,2987,360,False,False,3157,3089,6655,4645,3175,3152,3340,0,0,12,4,13,1,29,0,DUO,TOP,MIDDLE,True,False,200,Briar,39,43,53,67078,153028,199,43,39,51,78895,157464,165,-4,-11817,-4436,34,True,1,False,3,True,3,True,1,False,0,False,5,False,1,True,2,False,0,False,0,True,3,True,11,1,0,3,1,-3,-6
7,NA1_5551610911,1777692011461,1729,1777692023037,1777693752433,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,91,Talon,0,14707,209,36,245,8.502024,7,5,9,False,3.200000,340770,20073,0,38093,15580,387,False,False,3142,6697,6699,3158,3179,3134,3364,0,0,11,4,3,4,23,1,NONE,JUNGLE,JUNGLE,True,False,100,Akshan,38,33,43,67040,126317,164,33,38,39,62086,108007,176,5,4954,18310,-12,True,1,True,4,True,3,True,1,True,1,True,9,False,0,False,0,False,0,False,0,False,0,False,4,4,1,3,1,1,5
8,NA1_5551592126,1777690787592,918,1777690803483,1777691721658,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,76,Nidalee,0,7047,126,4,130,8.496732,3,1,8,False,11.000000,131310,5433,0,14755,9076,231,False,True,3152,1026,1001,1082,2022,1052,3364,0,0,11,4,4,0,12,0,SUPPORT,NONE,JUNGLE,True,False,200,Soraka,20,4,29,33245,40682,75,4,20,5,23668,28439,62,16,9577,12243,13,False,0,True,2,False,0,False,0,False,0,True,2,False,0,False,0,True,3,False,0,False,0,False,0,2,0,-3,0,0,2
9,NA1_5551033998,1777611354775,1529,1777611373749,1777612902239,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,91,Talon,0,18249,214,24,238,9.339438,18,0,5,False,23.000000,323892,32911,0,32926,19877,364,False,False,3142,3158,6697,6699,6694,1038,3364,0,0,11,4,0,2,19,0,NONE,JUNGLE,JUNGLE,True,False,200,Viktor,30,17,38,62438,92042,121,17,30,15,46109,82397,135,13,16329,9645,-14,True,1,True,3,False,0,True,1,True,1,True,10,False,0,False,1,True,3,False,0,False,0,False,2,2,1,-3,1,1,8
10,NA1_5551004026,1777609027040,2027,1777609048498,1777611075199,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,20,Nunu,0,16590,182,33,215,6.364085,15,8,19,False,4.250000,305388,35801,0,55618,28282,819,False,False,3110,6653,3111,2504,6665,3076,3364,0,0,11,4,9,3,28,0,NONE,JUNGLE,JUNGLE,False,True,200,Fiora,56,42,107,75134,165731,198,42,56,46,72499,159825,224,14,2635,5906,-26,True,2,True,4,False,0,True,1,True,1,False,8,False,0,False,1,True,3,False,0,False,0,True,5,3,2,-3,1,1,3
11,NA1_5550983463,1777607638153,1122,1777607711714,1777608834360,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,950,Naafiri,0,8951,115,28,143,7.647059,8,5,2,False,2.000000,142273,9651,0,14156,4523,177,False,True,3035,6697,6696,2422,3133,0,3364,0,0,11,4,1,4,15,0,SUPPORT,NONE,JUNGLE,False,True,100,Kaisa,16,27,16,34331,50622,76,27,16,32,42185,52039,67,-11,-7854,-1417,9,False,0,False,0,False,0,False,0,False,0,False,1,False,0,True,2,True,3,True,1,False,0,True,5,-2,0,-3,-1,0,-4
12,NA1_5550961002,1777605952469,1355,1777606038224,1777607393439,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,104,Graves,0,9750,131,51,182,8.059041,5,7,2,False,1.000000,191347,8722,0,16859,4000,326,False,True,6676,6697,1037,1001,6670,0,3364,0,0,11,4,2,8,21,0,NONE,JUNGLE,JUNGLE,True,False,200,Aatrox,15,31,22,42924,65272,143,31,15,49,54806,84716,137,-16,-11882,-19444,6,False,0,False,0,False,0,False,0,False,0,False,1,True,1,True,3,True,3,True,1,True,1,True,7,-3,-1,-3,-1,-1,-6
13,NA1_5550933013,1777604016786,1558,1777604037486,1777605595144,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,799,Ambessa,0,11948,154,22,176,6.777920,6,7,7,False,1.857143,231882,21266,0,29725,10442,321,False,True,6698,6610,1001,6333,3035,0,3364,0,0,11,4,6,2,24,1,NONE,JUNGLE,JUNGLE,True,False,200,Irelia,27,42,37,56041,123625,121,42,27,49,61415,123631,129,-15,-5374,-6,-8,False,0,True,1,True,3,False,0,False,0,False,4,False,0,False,2,False,0,True,1,True,1,True,7,-1,0,3,-1,-1,-3
14,NA1_5550675597,1777582298128,1483,1777582314611,1777583797772,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,121,Khazix,0,10780,152,13,165,6.675657,3,6,4,False,1.166667,212903,10064,0,23400,10181,246,False,True,3179,6697,1001,3814,1036,0,3364,0,0,11,4,2,2,15,0,NONE,JUNGLE,JUNGLE,False,True,100,Renekton,23,21,30,54438,81909,129,21,24,24,47190,73424,122,2,7248,8485,7,True,1,False,1,False,0,False,0,False,0,False,6,False,0,True,2,True,3,True,1,False,0,True,3,-1,1,-3,-1,0,3
15,NA1_5550663724,1777580807175,1254,1777580824770,1777582078816,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,120,Hecarim,0,11548,193,26,219,10.478469,8,2,4,False,6.000000,273490,12914,0,23983,15804,188,False,True,3071,3008,6699,3133,1037,2055,3364,0,0,11,6,1,1,11,0,NONE,JUNGLE,JUNGLE,False,True,200,Ryze,23,7,27,45748,52371,116,7,23,10,36012,38493,106,16,9736,13878,10,True,1,True,3,False,0,True,1,False,0,True,4,False,0,False,0,True,3,False,0,False,0,False,0,3,1,-3,1,0,4
16,NA1_5550651917,1777578815559,1691,1777578828166,1777580519717,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,799,Ambessa,0,14420,166,28,194,6.883501,8,5,16,False,4.800000,273548,33163,0,34026,15121,417,False,False,6698,6610,6333,3047,1036,1036,3364,0,0,11,4,3,2,14,0,NONE,JUNGLE,JUNGLE,False,True,100,Tristana,38,25,81,66312,129627,176,25,38,20,56209,91263,155,13,10103,38364,21,True,1,False,2,False,0,False,0,True,2,False,9,False,0,True,2,True,3,True,1,False,0,True,5,0,1,-3,-1,2,4
17,NA1_5550638975,1777577166427,1384,1777577184898,1777578564019,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,799,Ambessa,0,10149,126,22,148,6.416185,4,8,3,False,0.875000,177955,12995,0,21287,6242,227,False,True,6698,6695,1001,6333,2022,1036,3364,0,0,11,4,2,2,13,0,NONE,JUNGLE,JUNGLE,False,True,200,Nami,12,38,11,43601,59588,86,38,12,37,54327,94835,113,-26,-10726,-35247,-27,False,0,False,0,True,3,False,0,False,0,False,2,True,1,True,2,False,0,True,1,False,0,True,7,-2,-1,3,-1,0,-5
18,NA1_5550623077,1777574896178,1922,1777574992351,1777576914807,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,104,Graves,0,13503,204,21,225,7.023933,3,11,12,False,1.363636,313113,24459,0,31078,7210,586,False,False,6676,3036,3047,6670,1018,6697,3364,0,0,11,4,3,2,20,1,NONE,JUNGLE,JUNGLE,True,False,200,Yunara,36,43,61,67463,143886,161,43,36,68,77872,125484,208,-7,-10409,18402,-47,True,1,False,2,False,0,True,1,False,0,True,2,False,1,True,3,True,3,False,0,True,1,False,11,-1,0,-3,1,-1,-9
19,NA1_5550609094,1777572833995,1833,1777572863070,1777574696004,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,799,Ambessa,0,16942,177,38,215,7.037643,12,5,14,False,5.200000,300085,31745,0,38198,16754,448,False,True,6698,6610,3111,6333,3156,1038,3364,0,0,11,4,5,1,20,0,NONE,JUNGLE,JUNGLE,True,False,100,Viego,49,27,59,71134,128173,188,27,49,40,61986,110503,185,22,9148,17670,3,True,1,True,1,False,0,True,1,True,2,True,10,False,0,False,2,True,3,False,0,False,0,False,3,-1,1,-3,1,2,7
20,NA1_5550595425,1777570851158,1603,1777571035444,1777572638847,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,799,Ambessa,0,12602,180,29,209,7.822832,5,4,8,False,3.250000,264099,21130,0,28322,12728,394,False,True,6698,6610,6333,3047,2019,1036,3364,0,0,11,4,2,4,21,1,NONE,JUNGLE,JUNGLE,False,False,None,None,18,39,29,52936,83005,143,38,18,46,62423,110057,185,-20,-9487,-27052,-42,False,0,False,0,True,3,False,0,False,0,False,2,True,1,True,4,False,0,True,1,True,1,True,7,-4,-1,3,-1,-1,-5
21,NA1_5550457665,1777533149686,921,1777533233323,1777534154098,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,799,Ambessa,0,5538,84,17,101,6.579805,3,3,0,False,1.000000,97255,4631,0,12472,4877,167,False,True,6698,1101,2422,2021,1028,0,3364,0,0,11,4,2,1,7,1,SUPPORT,NONE,JUNGLE,False,True,200,Bard,7,21,5,24000,27183,48,21,7,25,32838,42846,67,-14,-8838,-15663,-19,False,0,False,0,False,0,False,0,False,0,False,0,False,0,True,2,True,3,False,0,False,0,True,2,-2,0,-3,0,0,-2
22,NA1_5550447653,1777531679532,1061,1777531708133,1777532766078,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,799,Ambessa,0,9716,142,14,156,8.821866,9,0,3,False,12.000000,178234,10035,0,12674,8675,252,False,True,6698,6610,2019,1036,2422,1036,3513,0,0,11,4,0,0,4,0,SUPPORT,NONE,JUNGLE,False,True,200,Jhin,16,13,21,36025,45652,69,13,16,10,32302,36879,42,3,3723,8773,27,False,0,True,2,True,2,True,1,False,0,False,2,False,0,False,0,False,1,False,0,False,0,True,2,2,0,1,1,0,0
23,NA1_5550424411,1777528740543,2620,1777528760747,1777531380841,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,121,Khazix,0,22889,241,33,274,6.274809,21,11,14,False,3.181818,417415,48437,0,55025,19087,315,False,False,3179,6697,3047,6694,3814,6695,3364,0,0,11,4,4,5,34,1,NONE,JUNGLE,JUNGLE,False,True,200,Qiyana,51,44,101,93541,198890,281,44,51,55,89063,204315,281,7,4478,-5425,0,False,1,False,1,True,3,True,1,False,1,False,8,True,2,True,5,False,0,False,0,True,2,True,11,-4,-1,3,1,-1,-3
24,NA1_5550400671,1777526634619,1547,1777526651786,1777528198470,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,432,Bard,0,10291,0,26,26,1.008403,5,2,22,True,13.500000,41459,18942,0,17961,6286,359,False,False,3869,3742,6653,3086,3009,3144,3364,0,0,3,4,28,4,66,1,SUPPORT,BOTTOM,UTILITY,True,False,100,Bard,42,18,59,62124,108984,160,18,42,24,52303,88327,134,24,9821,20657,26,True,1,False,3,False,0,True,1,True,3,True,10,False,0,True,1,True,3,False,0,False,0,False,2,2,1,-3,1,3,8
25,NA1_5550371651,1777524120963,1830,1777524145176,1777525975648,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,63,Brand,0,11003,1,78,79,2.590164,4,16,14,False,1.125000,72207,20523,0,33532,695,366,False,False,3871,2503,3020,3116,3165,1052,3364,0,0,3,4,27,7,82,0,SOLO,BOTTOM,UTILITY,False,True,100,Jhin,34,56,49,66244,118613,163,56,34,60,77316,154363,181,-22,-11072,-35750,-18,False,0,False,2,False,0,False,0,False,0,False,3,True,1,True,3,True,3,False,0,True,1,True,10,-1,-1,-3,0,-1,-7
26,NA1_5550346448,1777522128744,1529,1777522154388,1777523683860,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,799,Ambessa,0,10871,173,15,188,7.377371,2,7,4,False,0.857143,237467,14670,0,24914,9500,388,False,False,6698,6610,2019,3133,1033,2422,3364,0,0,11,4,4,1,15,1,NONE,JUNGLE,JUNGLE,False,True,100,Fizz,14,38,18,45642,92019,168,38,14,60,60857,110767,187,-24,-15215,-18748,-19,False,0,True,1,True,2,False,0,False,0,False,2,True,1,False,2,False,1,True,1,True,2,True,9,-1,-1,1,-1,-2,-7
27,NA1_5550322390,1777520403395,1421,1777520417800,1777521839025,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,799,Ambessa,0,13906,203,21,224,9.458128,13,1,5,False,18.000000,276388,27903,0,27277,17955,414,False,True,6698,6610,3047,6333,1038,2019,3364,0,0,11,4,4,2,21,1,NONE,JUNGLE,JUNGLE,False,True,200,Kindred,30,26,36,54441,93155,133,26,30,26,46107,88911,126,4,8334,4244,7,False,0,True,3,False,0,False,0,True,1,True,8,False,0,False,0,True,1,False,0,False,0,False,1,3,0,-1,0,1,7
28,NA1_5550296098,1777518520402,1549,1777518545339,1777520094131,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,799,Ambessa,0,10563,167,47,214,8.289219,4,4,6,True,2.500000,257310,22610,0,33434,12136,305,False,False,6698,6610,6333,1036,1036,2422,3364,0,0,11,4,0,4,15,0,NONE,JUNGLE,JUNGLE,True,False,100,Ambessa,20,31,40,45148,92062,142,31,20,56,58120,125496,141,-11,-12972,-33434,1,False,0,False,0,False,0,True,1,False,0,False,1,True,1,True,4,True,3,False,0,True,2,True,9,-4,-1,-3,1,-2,-8
29,NA1_5550259747,1777516061860,2150,1777516088603,1777518238410,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,91,Talon,0,19657,233,50,283,7.897674,12,5,11,False,4.600000,380452,34566,0,44468,20843,380,False,True,3142,6697,3158,6333,3814,6694,3364,0,0,11,4,3,3,30,0,NONE,JUNGLE,JUNGLE,False,True,200,Khazix,31,38,47,75385,120445,227,38,31,47,81348,159275,222,-7,-5963,-38830,5,True,1,True,1,True,2,False,0,False,0,False,7,False,0,False,3,False,1,True,1,True,1,True,9,-2,1,1,-1,-1,-2

In [871]:
import os
from dotenv import load_dotenv
load_dotenv()

from sqlalchemy import create_engine
from pangres import upsert

db_username = os.environ.get('dbusername')
db_password = os.environ.get('dbpassword')
db_host = os.environ.get('db_host')
db_port = os.environ.get('db_port')
db_name = os.environ.get('db_name')

def create_db_connection_url(db_username, db_password, db_host, db_port, db_name):
    connection_url = 'postgresql+psycopg2://' + db_username + ':' + db_password + '@' + db_host + ':' + db_port + '/' + db_name
    return connection_url

con_url = create_db_connection_url(db_username, db_password, db_host, db_port, db_name)

db_engine = create_engine(con_url, pool_recycle=3600)

connection = db_engine.connect()

In [872]:
df['uuid'] = df['match_id'] + '_' + df['puuid']
df = df.set_index('uuid')

In [873]:
df

,match_id,game_creation,game_duration,game_start_timestamp,game_end_timestamp,patch,puuid,riot_id,riot_tag,summoner_id,summoner_name,win,team_id,enemy_team_id,side,champion_id,champion_name,champion_transform,gold_earned,neutral_minions_killed,total_minions_killed,cs_total,cs_per_min,kills,deaths,assists,firstblood,kda,total_damage_dealt,total_damage_dealt_to_champions,total_damage_shielded,total_damage_taken,total_heal,total_time_cc_dealt,early_surrender,surrender,item0,item1,item2,item3,item4,item5,item6,objectives_stolen,objectives_stolen_assists,summoner1_id,summoner2_id,wards_placed,wards_killed,vision_score,detector_wards_placed,role,lane,team_position,team_first_blood,enemy_first_blood,first_blood_team_id,first_blood_champion,team_kills,team_deaths,team_assists,team_gold,team_damage_to_champions,team_vision_score,enemy_kills,enemy_deaths,enemy_assists,enemy_gold,enemy_damage_to_champions,enemy_vision_score,kill_difference,gold_difference,damage_difference,vision_difference,baron_first,baron_kills,dragon_first,dragon_kills,grub_first,grub_kills,herald_first,herald_kills,inhibitor_first,inhibitor_kills,tower_first,tower_kills,enemy_baron_first,enemy_baron_kills,enemy_dragon_first,enemy_dragon_kills,enemy_grub_first,enemy_grub_kills,enemy_herald_first,enemy_herald_kills,enemy_inhibitor_first,enemy_inhibitor_kills,enemy_tower_first,enemy_tower_kills,dragon_difference,baron_difference,grub_difference,herald_difference,inhibitor_difference,tower_difference
uuid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
NA1_5552207012_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5552207012,1777768479842,1397,1777768493326,1777769890811,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,134,Syndra,0,10651,0,189,189,8.117394,4,4,10,False,3.500000,136392,18478,0,16550,2210,490,False,False,2031,2503,1056,3173,4645,0,3363,0,0,12,4,8,0,15,0,SOLO,MIDDLE,MIDDLE,False,True,100,Aatrox,34,23,42,55656,97607,116,23,35,31,45026,79342,91,11,10630,18265,25,True,1,True,3,True,3,False,0,True,2,False,9,False,0,False,0,False,0,True,1,False,0,True,3,3,1,3,-1,2,6
NA1_5552174640_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5552174640,1777766039424,1963,1777766061627,1777768024695,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,799,Ambessa,0,14653,201,36,237,7.244014,8,9,4,False,1.333333,323024,22989,0,37025,13622,423,False,False,6698,6610,1036,6694,6333,3047,3364,0,0,11,4,12,4,35,3,NONE,JUNGLE,JUNGLE,True,False,100,Anivia,38,43,34,66321,134586,219,43,38,76,74915,129806,220,-5,-8594,4780,-1,True,1,False,1,True,3,True,1,False,0,True,4,False,0,True,4,False,0,False,0,True,3,False,11,-3,1,3,1,-3,-7
NA1_5552145422_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5552145422,1777763384816,2192,1777763402998,1777765594625,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,799,Ambessa,0,15056,210,59,269,7.363139,4,9,7,False,1.222222,348470,24777,0,44525,16441,419,False,False,6698,6610,3156,3111,1036,6333,3364,0,0,11,4,3,3,29,2,NONE,JUNGLE,JUNGLE,False,True,200,Zed,28,43,41,70738,128137,251,43,28,71,79266,184677,217,-15,-8528,-56540,34,False,0,True,1,True,3,False,0,False,0,False,4,True,1,False,4,False,0,True,1,True,1,True,8,-3,-1,3,-1,-1,-4
NA1_5552124829_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5552124829,1777761201033,1921,1777761219067,1777763140324,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,876,Lillia,0,18780,224,53,277,8.651744,15,5,16,False,6.200000,392004,44491,0,50301,32221,551,False,False,3157,6653,4633,3041,3047,3089,3364,0,0,11,4,6,1,20,0,NONE,JUNGLE,JUNGLE,False,True,100,Ezreal,40,33,59,76010,139459,191,33,40,32,65996,136116,232,7,10014,3343,-41,False,0,False,2,False,0,False,0,True,3,False,11,True,1,True,2,True,3,False,0,False,0,True,6,0,-1,-3,0,3,5
NA1_5551721292_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5551721292,1777699609356,1574,1777699629509,1777701203202,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,799,Ambessa,0,12611,187,19,206,7.852605,10,1,7,False,17.000000,279039,24308,0,23594,14112,360,False,True,6698,6696,6333,3047,3035,1036,3364,0,0,11,4,2,2,18,0,NONE,JUNGLE,JUNGLE,False,True,200,Anivia,32,10,42,58469,92384,132,10,32,16,43314,66793,117,22,15155,25591,15,False,0,False,2,True,3,True,1,True,1,True,8,False,0,True,2,False,0,False,0,False,0,False,1,0,0,3,1,1,7
NA1_5551699103_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5551699103,1777697824883,1561,1777697838895,1777699400479,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,91,Talon,0,10949,153,22,175,6.726457,4,8,5,False,1.125000,199725,10950,0,26646,7713,344,False,False,6699,6697,1001,3179,1036,0,3364,0,0,11,4,0,2,10,0,NONE,JUNGLE,JUNGLE,False,True,100,KSante,12,35,21,48329,86190,138,35,12,56,61391,87648,158,-23,-13062,-1458,-20,False,0,True,1,False,0,False,0,False,0,False,3,True,1,False,3,True,3,True,1,True,1,True,9,-2,-1,-3,-1,-1,-6
NA1_5551643180_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5551643180,1777694100558,1950,1777694116951,1777696066872,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,61,Orianna,0,18533,0,212,212,6.523077,20,7,12,False,4.571429,227630,58433,3356,28517,2987,360,False,False,3157,3089,6655,4645,3175,3152,3340,0,0,12,4,13,1,29,0,DUO,TOP,MIDDLE,True,False,200,Briar,39,43,53,67078,153028,199,43,39,51,78895,157464,165,-4,-11817,-4436,34,True,1,False,3,True,3,True,1,False,0,False,5,False,1,True,2,False,0,False,0,True,3,True,11,1,0,3,1,-3,-6
NA1_5551610911_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5551610911,1777692011461,1729,1777692023037,1777693752433,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,91,Talon,0,14707,209,36,245,8.502024,7,5,9,False,3.200000,340770,20073,0,38093,15580,387,False,False,3142,6697,6699,3158,3179,3134,3364,0,0,11,4,3,4,23,1,NONE,JUNGLE,JUNGLE,True,False,100,Akshan,38,33,43,67040,126317,164,33,38,39,62086,108007,176,5,4954,18310,-12,True,1,True,4,True,3,True,1,True,1,True,9,False,0,False,0,False,0,False,0,False,0,False,4,4,1,3,1,1,5
NA1_5551592126_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5551592126,1777690787592,918,1777690803483,1777691721658,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,76,Nidalee,0,7047,126,4,130,8.496732,3,1,8,False,11.000000,131310,5433,0,14755,9076,231,False,True,3152,1026,1001,1082,2022,1052,3364,0,0,11,4,4,0,12,0,SUPPORT,NONE,JUNGLE,True,False,200,Soraka,20,4,29,33245,40682,75,4,20,5,23668,28439,62,16,9577,12243,13,False,0,True,2,False,0,False,0,False,0,True,2,False,0,False,0,True,3,False,0,False,0,False,0,2,0,-3,0,0,2
NA1_5551033998_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5551033998,1777611354775,1529,1777611373749,1777612902239,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,91,Talon,0,18249,214,24,238,9.339438,18,0,5,False,23.000000,323892,32911,0,32926,19877,364,False,False,3142,3158,6697,6699,6694,1038,3364,0,0,11,4,0,2,19,0,NONE,JUNGLE,JUNGLE,True,False,200,Viktor,30,17,38,62438,92042,121,17,30,15,46109,82397,135,13,16329,9645,-14,True,1,True,3,False,0,True,1,True,1,True,10,False,0,False,1,True,3,False,0,False,0,False,2,2,1,-3,1,1,8
NA1_5551004026_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5551004026,1777609027040,2027,1777609048498,1777611075199,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,20,Nunu,0,16590,182,33,215,6.364085,15,8,19,False,4.250000,305388,35801,0,55618,28282,819,False,False,3110,6653,3111,2504,6665,3076,3364,0,0,11,4,9,3,28,0,NONE,JUNGLE,JUNGLE,False,True,200,Fiora,56,42,107,75134,165731,198,42,56,46,72499,159825,224,14,2635,5906,-26,True,2,True,4,False,0,True,1,True,1,False,8,False,0,False,1,True,3,False,0,False,0,True,5,3,2,-3,1,1,3
NA1_5550983463_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550983463,1777607638153,1122,1777607711714,1777608834360,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,950,Naafiri,0,8951,115,28,143,7.647059,8,5,2,False,2.000000,142273,9651,0,14156,4523,177,False,True,3035,6697,6696,2422,3133,0,3364,0,0,11,4,1,4,15,0,SUPPORT,NONE,JUNGLE,False,True,100,Kaisa,16,27,16,34331,50622,76,27,16,32,42185,52039,67,-11,-7854,-1417,9,False,0,False,0,False,0,False,0,False,0,False,1,False,0,True,2,True,3,True,1,False,0,True,5,-2,0,-3,-1,0,-4
NA1_5550961002_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550961002,1777605952469,1355,1777606038224,1777607393439,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,104,Graves,0,9750,131,51,182,8.059041,5,7,2,False,1.000000,191347,8722,0,16859,4000,326,False,True,6676,6697,1037,1001,6670,0,3364,0,0,11,4,2,8,21,0,NONE,JUNGLE,JUNGLE,True,False,200,Aatrox,15,31,22,42924,65272,143,31,15,49,54806,84716,137,-16,-11882,-19444,6,False,0,False,0,False,0,False,0,False,0,False,1,True,1,True,3,True,3,True,1,True,1,True,7,-3,-1,-3,-1,-1,-6
NA1_5550933013_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550933013,1777604016786,1558,1777604037486,1777605595144,16.9.772.1032,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,799,Ambessa,0,11948,154,22,176,6.777920,6,7,7,False,1.857143,231882,21266,0,29725,10442,321,False,True,6698,6610,1001,6333,3035,0,3364,0,0,11,4,6,2,24,1,NONE,JUNGLE,JUNGLE,True,False,200,Irelia,27,42,37,56041,123625,121,42,27,49,61415,123631,129,-15,-5374,-6,-8,False,0,True,1,True,3,False,0,False,0,False,4,False,0,False,2,False,0,True,1,True,1,True,7,-1,0,3,-1,-1,-3
NA1_5550675597_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550675597,1777582298128,1483,1777582314611,1777583797772,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,121,Khazix,0,10780,152,13,165,6.675657,3,6,4,False,1.166667,212903,10064,0,23400,10181,246,False,True,3179,6697,1001,3814,1036,0,3364,0,0,11,4,2,2,15,0,NONE,JUNGLE,JUNGLE,False,True,100,Renekton,23,21,30,54438,81909,129,21,24,24,47190,73424,122,2,7248,8485,7,True,1,False,1,False,0,False,0,False,0,False,6,False,0,True,2,True,3,True,1,False,0,True,3,-1,1,-3,-1,0,3
NA1_5550663724_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550663724,1777580807175,1254,1777580824770,1777582078816,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,120,Hecarim,0,11548,193,26,219,10.478469,8,2,4,False,6.000000,273490,12914,0,23983,15804,188,False,True,3071,3008,6699,3133,1037,2055,3364,0,0,11,6,1,1,11,0,NONE,JUNGLE,JUNGLE,False,True,200,Ryze,23,7,27,45748,52371,116,7,23,10,36012,38493,106,16,9736,13878,10,True,1,True,3,False,0,True,1,False,0,True,4,False,0,False,0,True,3,False,0,False,0,False,0,3,1,-3,1,0,4
NA1_5550651917_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550651917,1777578815559,1691,1777578828166,1777580519717,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,200,100,red,799,Ambessa,0,14420,166,28,194,6.883501,8,5,16,False,4.800000,273548,33163,0,34026,15121,417,False,False,6698,6610,6333,3047,1036,1036,3364,0,0,11,4,3,2,14,0,NONE,JUNGLE,JUNGLE,False,True,100,Tristana,38,25,81,66312,129627,176,25,38,20,56209,91263,155,13,10103,38364,21,True,1,False,2,False,0,False,0,True,2,False,9,False,0,True,2,True,3,True,1,False,0,True,5,0,1,-3,-1,2,4
NA1_5550638975_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550638975,1777577166427,1384,1777577184898,1777578564019,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,799,Ambessa,0,10149,126,22,148,6.416185,4,8,3,False,0.875000,177955,12995,0,21287,6242,227,False,True,6698,6695,1001,6333,2022,1036,3364,0,0,11,4,2,2,13,0,NONE,JUNGLE,JUNGLE,False,True,200,Nami,12,38,11,43601,59588,86,38,12,37,54327,94835,113,-26,-10726,-35247,-27,False,0,False,0,True,3,False,0,False,0,False,2,True,1,True,2,False,0,True,1,False,0,True,7,-2,-1,3,-1,0,-5
NA1_5550623077_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550623077,1777574896178,1922,1777574992351,1777576914807,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,104,Graves,0,13503,204,21,225,7.023933,3,11,12,False,1.363636,313113,24459,0,31078,7210,586,False,False,6676,3036,3047,6670,1018,6697,3364,0,0,11,4,3,2,20,1,NONE,JUNGLE,JUNGLE,True,False,200,Yunara,36,43,61,67463,143886,161,43,36,68,77872,125484,208,-7,-10409,18402,-47,True,1,False,2,False,0,True,1,False,0,True,2,False,1,True,3,True,3,False,0,True,1,False,11,-1,0,-3,1,-1,-9
NA1_5550609094_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550609094,1777572833995,1833,1777572863070,1777574696004,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,799,Ambessa,0,16942,177,38,215,7.037643,12,5,14,False,5.200000,300085,31745,0,38198,16754,448,False,True,6698,6610,3111,6333,3156,1038,3364,0,0,11,4,5,1,20,0,NONE,JUNGLE,JUNGLE,True,False,100,Viego,49,27,59,71134,128173,188,27,49,40,61986,110503,185,22,9148,17670,3,True,1,True,1,False,0,True,1,True,2,True,10,False,0,False,2,True,3,False,0,False,0,False,3,-1,1,-3,1,2,7
NA1_5550595425_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550595425,1777570851158,1603,1777571035444,1777572638847,16.9.771.8383,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,799,Ambessa,0,12602,180,29,209,7.822832,5,4,8,False,3.250000,264099,21130,0,28322,12728,394,False,True,6698,6610,6333,3047,2019,1036,3364,0,0,11,4,2,4,21,1,NONE,JUNGLE,JUNGLE,False,False,None,None,18,39,29,52936,83005,143,38,18,46,62423,110057,185,-20,-9487,-27052,-42,False,0,False,0,True,3,False,0,False,0,False,2,True,1,True,4,False,0,True,1,True,1,True,7,-4,-1,3,-1,-1,-5
NA1_5550457665_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550457665,1777533149686,921,1777533233323,1777534154098,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,100,200,blue,799,Ambessa,0,5538,84,17,101,6.579805,3,3,0,False,1.000000,97255,4631,0,12472,4877,167,False,True,6698,1101,2422,2021,1028,0,3364,0,0,11,4,2,1,7,1,SUPPORT,NONE,JUNGLE,False,True,200,Bard,7,21,5,24000,27183,48,21,7,25,32838,42846,67,-14,-8838,-15663,-19,False,0,False,0,False,0,False,0,False,0,False,0,False,0,True,2,True,3,False,0,False,0,True,2,-2,0,-3,0,0,-2
NA1_5550447653_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550447653,1777531679532,1061,1777531708133,1777532766078,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,799,Ambessa,0,9716,142,14,156,8.821866,9,0,3,False,12.000000,178234,10035,0,12674,8675,252,False,True,6698,6610,2019,1036,2422,1036,3513,0,0,11,4,0,0,4,0,SUPPORT,NONE,JUNGLE,False,True,200,Jhin,16,13,21,36025,45652,69,13,16,10,32302,36879,42,3,3723,8773,27,False,0,True,2,True,2,True,1,False,0,False,2,False,0,False,0,False,1,False,0,False,0,True,2,2,0,1,1,0,0
NA1_5550424411_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550424411,1777528740543,2620,1777528760747,1777531380841,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,121,Khazix,0,22889,241,33,274,6.274809,21,11,14,False,3.181818,417415,48437,0,55025,19087,315,False,False,3179,6697,3047,6694,3814,6695,3364,0,0,11,4,4,5,34,1,NONE,JUNGLE,JUNGLE,False,True,200,Qiyana,51,44,101,93541,198890,281,44,51,55,89063,204315,281,7,4478,-5425,0,False,1,False,1,True,3,True,1,False,1,False,8,True,2,True,5,False,0,False,0,True,2,True,11,-4,-1,3,1,-1,-3
NA1_5550400671_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550400671,1777526634619,1547,1777526651786,1777528198470,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,True,100,200,blue,432,Bard,0,10291,0,26,26,1.008403,5,2,22,True,13.500000,41459,18942,0,17961,6286,359,False,False,3869,3742,6653,3086,3009,3144,3364,0,0,3,4,28,4,66,1,SUPPORT,BOTTOM,UTILITY,True,False,100,Bard,42,18,59,62124,108984,160,18,42,24,52303,88327,134,24,9821,20657,26,True,1,False,3,False,0,True,1,True,3,True,10,False,0,True,1,True,3,False,0,False,0,False,2,2,1,-3,1,3,8
NA1_5550371651_BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,NA1_5550371651,1777524120963,1830,1777524145176,1777525975648,16.9.769.5709,BMi4CNpKIhEFggSmMTqSox661sMW2DGvueZ8O_jqJ_zM29GfX_8vbw5q-SacpCxpIDwlxFSBw_Iqew,KataIina,NA1,uu7a_UQZ215o3IvNhYwqRwGyta6SwITnBYaz-WzJCOMzpLAJ,,False,200,100,red,63,Brand,0,11003,1,78,79,2.590164,4,16,14,False,1.125000,72207,20523,0,33532,695,366,False,False,3871,2503,3020,3116,3165,1052,3364,0,0,3,4,27,7,82,0,SOLO,BOTTOM,UTILITY,False,True,100,Jhin,34,56,49,66244,118613,163,56,34,60,77316,154363,181,-22,-11072,-35750,-18,False,0,False,2,False,0,False,0,False,0,False,3,True,1,True,3,True,3,False,0,True,1,True,10,-1,-1,-3,0,-1,-7

In [874]:
upsert(con=connection, df=df, schema='soloq', table_name='match_data', create_table=True, create_schema=True, if_row_exists='update')

In [875]:
connection.commit()